name: Sock Shop CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io  # Change to your registry (quay.io, harbor.yourdomain.com, etc.)
  IMAGE_NAME: anisky/shock-shop  # Uses your GitHub repo name or set a custom name
  VERSION: ${{ github.sha }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Print working directory
      run: |
        echo "Current working directory: $(pwd)"
        echo "Directory contents:"
        ls -al
    
    - name: Build and push front-end
      uses: docker/build-push-action@v4
      with:
        context: src/front-end/
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/front-end:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/front-end:latest
    
    - name: Build and push cart
      uses: docker/build-push-action@v4
      with:
        context: sock-shop-demo/src/cart
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cart:${{ env.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cart:latest

    - name: Build and push other services
      run: |
        cd sock-shop-demo
        for service in catalogue currency payment shipping user queue-master; do
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$service:${{ env.VERSION }} src/$service
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$service:${{ env.VERSION }}
        done
